baseURL = 'https://strstr.0xdc.ru/'
title = 'Поиск подстроки в строке'
languageCode = 'ru-ru'

# Book configuration
disablePathToLower = false
enableGitInfo = true

disableKinds = ['taxonomy', 'taxonomyTerm']
relativeURLs = true

enableRobotsTXT = true

[sitemap]
  changefreq = 'weekly'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'vs'

[params]
  BookTheme = 'light'
  BookToC = false
  # BookLogo = 'logo.png'
  # BookMenuBundle = '/menu'
  BookSection = 'docs'
  BookRepo = 'https://github.com/illarionov/strstr'
  # BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
  BookDateFormat = '2006-01-23'
  BookSearch = false
  BookComments = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  # BookServiceWorker = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  # BookTranslatedOnly = false

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/illarionov/strstr"
  weight = 10

[math]
handler = "katex"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[[module.mounts]]
  source = 'static'
  target = 'static'
  excludeFiles = [
    'flexsearch\.min\.js'
  ]
