name: Check sample code

on:
  push:
      paths:
      -  'code/**'
  pull_request:
    paths:
      -  'code/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build and test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --stacktrace build
          build-root-directory: code/
          gradle-executable: code/gradlew

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: code/build/test-results/**/*.xml

      - name: Upload test tesults
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: |
            code/build/reports/
            code/build/test-results/**/*.xml